### ISSUE TITLE
[Chore] Reduce complexity of Api::V1::Reports::FetchKeywords

### ISSUE THREAD

**Issue by olivierobert** [tednguyendev/nimble_challenge#32]
## Issue

https://github.com/tednguyendev/nimble_challenge/blob/main/app/commands/api/v1/reports/fetch_keywords.rb does many things:
- Scheduling the scraping of keywords, i.e., he computation of delays
- Scraping the HTML content, i.e., recording the HTML content via Selenium and extracting all the required data points 
- Updating the corresponding report 

Not only it is a violation of the single responsibility principle (in SOLID), it makes the class long to read and understand. So there is room for improvement 🤝 

> **Note**
> The class name Api::V1::Reports::FetchKeywords does not describe what it does since it does way more than just fetching keywords 🙈 

## Expected

The business logic could be broken down into different objects:
- Keyword fetcher (the current class), i.e., schedule the scraping of one keyword (refer to #31)
- Scraper, i.e., Selenium-driven extraction of the HTML + logic for rotating user agents
- HTML content processor, i.e., parsing the HTML content + extracting the required data points

> **Note**
> The delayed computation could be done at the worker class level

> **Note**
> You might want to look into singleton to have a simple class/module returning the user agents: https://www.rubyguides.com/2018/05/singleton-pattern-in-ruby/

> **Note**
> Updating one model from another model is kind of unexpected:
> https://github.com/tednguyendev/nimble_challenge/blob/674be95873d58adda0e802a0d4528d1c234b1383/app/models/keyword.rb#L26-L33
> It would be best to leave this to the command object to handle how to update the progress, i.e., it should not be in the keyword model.

**Comment by tednguyendev** [comment]
Hi Olivier,

I understand. This fetch_keywords is doing a lot of things. Although I tried to make it shorter, it is true that we can even break down the code into more objects.

I have created a PR ([#37](https://github.com/tednguyendev/nimble_challenge/pull/36)) where I will make the necessary changes. Once the PR is merged, I will notify you.

I have one question about the "Updating one model from another model is kind of unexpected"

I understand what you meant, as putting the method `update_report_percentage` in the keyword model may bring some unpredictability. But if we put this code into the command object FetchKeywords, and if there is another command object in the feature that can also update the keywords and the ports the report, then should we put this `update_report_percentage` method into both command objects, instead of just in the keyword model?

**Comment by olivierobert** [comment]
Regarding your question, I don't have a one-size-fits-all answer for you. It depends 😅 

However, as a rule of thumb, when there is a single use for this logic, always prefer having it at the service/command layer. It helps to have less indirection and removes any unexpected side effects. If the code needs to be called by multiple objects, either there is one command/service object that others can call, or you can place the code in the report model. 

In most cases, prefer not to rely too much on model hooks unless there is a strong need for them.

**Comment by tednguyendev** [comment]
I understand! In this case, I now also think putting the `update_report_percentage` in the command is the better solution. Let me change it.

**Comment by tednguyendev** [comment]
Hi Olivier, I finished this PR. You can have a look at the PR [here](https://github.com/tednguyendev/nimble_challenge/pull/37).

Thank you!

**Comment by olivierobert** [comment]
I am unsure about the naming of the additional services but the separation of concerns is definitely an improvement 👍
