### ISSUE TITLE
[Question] Why using custom presenters for JSON responses?

### ISSUE THREAD

**Issue by olivierobert** [tednguyendev/nimble_challenge#33]
The current implementation (https://github.com/tednguyendev/nimble_challenge/blob/main/app/presenters/api/v1/base_presenter.rb) does not use either https://github.com/rails/jbuilder or https://github.com/rails-api/active_model_serializers, which are standardly used in most Ruby on Rails application. So it would be interesting to understand the rationale for "reinventing the wheel" in this case 😅 

> **Note**
> Another observation on this topic is that you could look into using decorators for this kind of code:
> https://github.com/tednguyendev/nimble_challenge/blob/674be95873d58adda0e802a0d4528d1c234b1383/app/models/report.rb#L28-L30

**Comment by tednguyendev** [comment]
Hi Olivier,

About the presenters, the main reason is that because this current project does not really require too many presenter features, so I find making a custom implementation is sufficient. And although the syntax of my custom presenter is more verbose, I find it easier to read and write because it is just plain ruby instead of any syntaxes of these libraries.

And this is just a personal preference, as I am well aware of and also have experience using standard libraries like Active Model Serializers or Grape Entity :D

About the decorator, thanks for advising me on that! I agree that using decorators for these kinds of code really will make our model files a lot cleaner! For this project, the reason I'm not using patterns like the decorator is just that I find our models are not very "fat" yet, but I will definitely utilize the power of the decorators once I see the chance!

**Comment by olivierobert** [comment]
All of this makes sense 😁 Thanks for for the explanation!
